Support addressShuffleMode to Spring Amqp Autoconfiguration
spring-projects/spring-boot pull request #23091
Opened 2020-08-26 11:47 UTC by 01045972746

This support connecting to RabbitMQ clustered host addresses with shuffling.
https://docs.spring.io/spring-amqp/reference/html/#cluster

Because of `shuffle-addresses` mode is deprecated, i have added `addressShuffleMode` property which is `String`.
Please review and comment. Thanks.

2020-08-26 11:58 UTC, snicoll requested changes
Thanks for the suggestion and the PR. I've made a few comments, can you please have a look to those and also add the necessary tests to exercise the code that you've changed?

2020-08-26 11:58 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java
> +	private String addressShuffleMode = "NONE";
The enum should be exposed rather as it provides better metadata

2020-08-26 11:58 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java
> +	 * Shuffling mode for connecting host. Default mode is NONE.
The default value should not be documented as it's the role of the configuration metadata to do that (look at other keys for inspiration).

2020-08-26 11:58 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java
> +	public AbstractConnectionFactory.AddressShuffleMode determineAddressShuffleMode() {
I don't think we should do that. Rather we should set whatever has been set by the user.

2020-08-26 13:03 UTC, 01045972746 commented
@snicoll , i have edited what you mention. please re-review plz.

2020-08-27 12:39 UTC, closed without merging

2020-08-27 12:40 UTC, snicoll commented
@01045972746 thank you for making your first contribution to Spring Boot. I've polished your contribution and added a test.