Changing the string null check to improve performance.
spring-projects/spring-boot pull request #23550
Opened 2020-10-01 03:13 UTC by sann3

isEmpty() gives **20-40%** more performance than "".equals().

String equals source code, 
```
public boolean equals(Object anObject) {
        if (this == anObject) {
            return true;
        }
        if (anObject instanceof String) {
            String aString = (String)anObject;
            if (coder() == aString.coder()) {
                return isLatin1() ? StringLatin1.equals(value, aString.value)
                                  : StringUTF16.equals(value, aString.value);
            }
        }
        return false;
    }
```

Operator instanceOf, class casting, 3 if statements, and all this is just to start the check if the string is actually empty. 

Now compare it with String.isEmpty():
```
public boolean isEmpty() {
    return value.length == 0;
}
```

If we increase the performance in the framework, automatically multiple projects get the benefit.

#hacktoberfest

2020-10-02 15:00 UTC, snicoll requested changes
Thanks for the PR. The concrete impact of the change can be argued as most of those aren't hot code paths. I've added a few comments, can you please review?

2020-10-03 02:36 UTC, sann3 commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java
> +		this.virtualHost = (virtualHost == null || virtualHost.isEmpty()) ? "/" : virtualHost;
Yes, I will update it hasLength method.

2020-10-03 02:37 UTC, sann3 commented on spring-boot-project/spring-boot-cli/src/main/java/org/springframework/boot/cli/command/shell/CommandCompleter.java
> +		if (commandName != null && !commandName.isEmpty()) {
Yes, I will update it with hasText method.

2020-10-03 02:38 UTC, sann3 commented on spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/intTest/projects/run-jvm-system-props/src/main/java/org/test/SampleApplication.java
> +		if (property2 != null && !property2.isEmpty()) {
Yes, here it is not about performance, its about best practise.

2020-10-05 08:51 UTC, closed without merging

2020-10-05 08:51 UTC, snicoll commented
@sann3 thanks for the follow-up and for making your first contribution to Spring Boot.