Add keyStoreAlgorithm and trustStoreAlgorithm configuration option to configure RabbitConnectionFactory
spring-projects/spring-boot pull request #24076
Opened 2020-11-09 05:35 UTC by topikachu

Add keyStoreAlgorithm and trustStoreAlgorithm to RabbitProperties and adopt at Rabbit AutoConfig.

2020-11-09 07:24 UTC, wilkinsona requested changes
Thanks very much for the pull request, @topikachu. I've left a few minor comments. If you have the time, please take a look at them and let us know what you think.

2020-11-09 07:24 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java
> +		 * Key stroe algorithm.
Small typo here. Should be "store" rather than "stroe".

2020-11-09 07:24 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java
> +		 * Trust stroe algorithm.
Small typo here. Should be "store" rather than "stroe".

2020-11-09 07:24 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java
> +		private String keyStoreAlgorithm;
The initial value of this field should be `SunX509`. This aligns it with Spring AMQP's default for the property.

2020-11-09 07:24 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java
> +		private String trustStoreAlgorithm;
The initial value of this field should be `SunX509`. This aligns it with Spring AMQP's default for the property.

2020-11-09 07:24 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/amqp/RabbitAutoConfigurationTests.java
> +	void enableSslWithValidateStoreAlgorithmShouldWork() throws Exception {
Small typo here. Should be "Valid" rather than "Validate".

2020-11-09 07:24 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/amqp/RabbitAutoConfigurationTests.java
> +	void enableSslWithInValidateStoreAlgorithmShouldFail() throws Exception {
Small typo here. Should be "Valid" rather than "Validate".

2020-11-09 07:24 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java
> +		 * Trust stroe algorithm.
Small typo here. Should be "store" rather than "stroe".

2020-11-09 07:24 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java
> +		 * Key stroe algorithm.
Small typo here. Should be "store" rather than "stroe".

2020-11-09 07:24 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java
> +		private String keyStoreAlgorithm;
This field's initial value should be `"SunX509"`, aligning it with Spring AMQP's default.

2020-11-09 07:24 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/RabbitProperties.java
> +		private String trustStoreAlgorithm;
This field's initial value should be `"SunX509"`, aligning it with Spring AMQP's default.

2020-11-09 10:20 UTC, wilkinsona approved these changes
Thanks very much for the updates, @topikachu.

2020-12-15 10:02 UTC, closed without merging

2020-12-15 10:02 UTC, snicoll commented
@topikachu thank you for making your first contribution to Spring Boot.