Implement URL support for ActiveMQ Artemis
spring-projects/spring-boot pull request #24302
Opened 2020-11-30 19:49 UTC by jbertram

See gh-10739

2020-11-30 19:49 UTC, pivotal-issuemaster commented
@jbertram Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24302)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24302) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-11-30 19:51 UTC, pivotal-issuemaster commented
@jbertram Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=24302)!

2020-12-01 17:17 UTC, kmandalas commented
@jbertram I see some minor code Formatting violations in CI build, for files `ArtemisConnectionFactoryFactory.java` and `rtemisAutoConfigurationTests.java`. I guess can be resolved by running `gradle format`

2020-12-01 18:36 UTC, jbertram commented
@kmandalas the CI build issues have been resolved.

2020-12-02 11:28 UTC, kmandalas commented
@pivotal-issuemaster @spring-issuemaster can we proceed with the merge?

2020-12-02 17:45 UTC, philwebb commented
@kmandalas We need to wait until we've created a 2.4.x branch before we can merge this.

2020-12-21 10:00 UTC, snicoll requested changes
Thanks @jbertram for the proposal. 

While I find the idea of deprecating host/port interesting, it doesn't really address the concerns that we've expressed on the original issue. I've added a few comments, can you please have a look?

2020-12-21 10:01 UTC, snicoll commented
I suspect it was flagged with merge amendments as we don't handle deprecated properties this way (don't worry we can take care of it while polishing).

2020-12-21 15:54 UTC, jbertram commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/artemis/ArtemisConnectionFactoryFactory.java
> +					NettyConnectorFactory.class.getName(), params);
I thought I had [already addressed](https://github.com/spring-projects/spring-boot/issues/10739#issuecomment-692794114) that concern. To be clear, I don't really see what the concern actually is. The URL and all of its parameters are turned into a `TransportConfiguration` behind the scenes. Everything that can be set directly via a `TransportConfiguration` can be set with URL parameters. In other words there is no "loss of control" that I can see as @wilkinsona mentioned.

This change makes the Artemis integration essentially equivalent to the [ActiveMQ 5.x integration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/activemq/ActiveMQConnectionFactoryFactory.java#L82) which in my opinion is how it should have been implemented in the first place.

2020-12-21 15:55 UTC, jbertram commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/artemis/ArtemisConnectionFactoryFactory.java
>  		String user = this.properties.getUser();
The user and password cannot be provided via the URL. Therefore those settings are not deprecated. Again, this is how [the ActiveMQ 5.x integration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/activemq/ActiveMQConnectionFactoryFactory.java#L82) is implemented (i.e. URL, username, & password).

2020-12-21 15:59 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/artemis/ArtemisConnectionFactoryFactory.java
> +					NettyConnectorFactory.class.getName(), params);
As far as I can see you did not hence why I am asking here. The code I've referenced makes an explicit setup using `NettyConnectorFactory`. As far as I can see we'd lose that as soon as an url is set.

2020-12-21 15:59 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/artemis/ArtemisConnectionFactoryFactory.java
>  		String user = this.properties.getUser();
Sorry, I thought the URL could be used to provide the username and password.

2020-12-21 16:06 UTC, jbertram commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/artemis/ArtemisConnectionFactoryFactory.java
> +					NettyConnectorFactory.class.getName(), params);
I guess I'm not following. What exactly is the concern with losing the explicit `NettyConnectorFactory` setup? The only thing which can be set there is host and port. The URL provides the ability to set host and port as well as any other property.

2020-12-21 16:25 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/artemis/ArtemisConnectionFactoryFactory.java
> +					NettyConnectorFactory.class.getName(), params);
> What exactly is the concern with losing the explicit NettyConnectorFactory setup?

That's most probably the source of the confusion. When a URL is set, no specific transport is set. When a host and port are set a `NettyConnectorFactory` transport is set. Looking a bit more  `NettyConnectorFactory` seems the default implementation anyway so we'd use that as well. 

That wasn't clear hence why we asked explicitly.

2020-12-21 16:33 UTC, jbertram commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/artemis/ArtemisConnectionFactoryFactory.java
> +					NettyConnectorFactory.class.getName(), params);
> When a URL is set, no specific transport is set.

That's not accurate. Which "transport" is used is determined by the URL's scheme.

There are only 2 `ConnectorFactory` implementations in Artemis - `NettyConnectorFactory` and `InVMConnectorFactory`. To use the `NettyConnectorFactory` you simply need to use the `tcp://` scheme in the URL. To use the `InVMConnectorFactory` you need to use the `vm://` scheme.

2020-12-21 16:43 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/artemis/ArtemisConnectionFactoryFactory.java
> +					NettyConnectorFactory.class.getName(), params);
> That's not accurate. 
Sorry, poor choice of words.

I meant that the auto-configuration doesn't do anything special when a broker url is set while it does something explicit (in code) when a host is set. We're very cautious to not introduce any inconsistency and the reason why I asked you here. 

Thanks for the follow-up and the feedback !

2020-12-21 16:44 UTC, snicoll approved these changes

2020-12-21 16:54 UTC, closed without merging

2020-12-21 16:57 UTC, snicoll commented
@jbertram thank you for your contribution. I've polished it to prevent users using the (now) deprecated property to get their host/port configuration ignored (which is a smell of you having to add an empty broker-url property [here](https://github.com/spring-projects/spring-boot/pull/24302/commits/b3372414d67820f2fcb455e28cc2ee7028765a5d#diff-548567bbe4e167b990f04940d66c2b533c81191ede75bc3e0caa15eb87e284faR130). We now rather check if no broker url is set by the user and if a host is set we configure as we previously did. Of course, if a broker url is set, we'll always use that and I've added an extra test to validate that scenario.

2020-12-21 17:05 UTC, jbertram commented
@snicoll, sounds great! Thanks for the review and help with polishing. Feel free to @ me on anything in the future related to Artemis that you may have questions about.

2020-12-21 17:06 UTC, snicoll commented
Will do, thanks again for the great support Justin.