Upgrade to Flyway 7.9.0 and support failOnMissingLocations
spring-projects/spring-boot pull request #26456
Opened 2021-05-13 18:39 UTC by kedar-joshi

Updated Flyway to v7.9.0 with following changes -

1. Added configuration support for property `ignoreMigrationPatterns` (v7.8.0).
1. Added configuration support for property `failOnMissingLocations` (v7.9.0).

2021-05-14 09:22 UTC, kedar-joshi commented
Hi,
I keep getting following exception because some of the properties require **Teams Edition** of Flyway. Any advice on how to fix this ?

```
Caused by: org.flywaydb.core.internal.license.FlywayTeamsUpgradeRequiredException: Flyway Teams Edition upgrade required: detectEncoding is not supported by Flyway Community Edition
Try Flyway Teams Edition for free: https://flywaydb.org/try-flyway-teams-edition
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDetectEncoding(ClassicConfiguration.java:826)
	at org.flywaydb.core.api.configuration.FluentConfiguration.detectEncoding(FluentConfiguration.java:663)
	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.configureDetectEncoding(FlywayAutoConfiguration.java:266)
	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.configureProperties(FlywayAutoConfiguration.java:260)
	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.flyway(FlywayAutoConfiguration.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
```

2021-05-14 16:29 UTC, nguyensach commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayProperties.java
> +	private boolean failOnMissingLocations = false;
```suggestion
	private boolean failOnMissingLocations;
```
Because boolean's default value is false.

2021-05-28 15:00 UTC, snicoll requested changes
Thanks for the PR. I've made some comments.

For consistency we order properties a certain way and we try to stick with that order for mapping and tests as well.

2021-05-28 15:00 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayProperties.java
> +	 * Whether or not Flyway should try to automatically detect SQL migration file
We use "Whether Flyway" everywhere else in this class. Can you please adapt for consistency?

2021-05-28 15:00 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayProperties.java
> +	 * encoding. Requires Flyway Teams.
Flyway teams properties are all aggregated at the end.

2021-05-28 15:00 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayProperties.java
> +	 * migrations. Requires Flyway Teams.
Flyway teams properties are all aggregated at the end.

2021-05-28 15:00 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayProperties.java
> +	private boolean failOnMissingLocations;
I would move this property next to the currently deprecated one rather than after all other properties

2021-05-28 15:00 UTC, snicoll commented on spring-boot-project/spring-boot-dependencies/build.gradle
> +	library("Flyway", "7.9.0") {
7.9.1 is out in the meantime so can you please upgrade to that?

2021-05-31 06:47 UTC, snicoll approved these changes
Thanks for the follow-up!

2021-06-14 06:25 UTC, closed without merging

2021-07-12 07:57 UTC, snicoll commented
I've migrated this one to an enhancement as we're upgrading to 7.11.1 in #27290