Allow custom RSocket WebsocketServerSpecs to be defined.
spring-projects/spring-boot pull request #29567
Opened 2022-01-26 02:59 UTC by polarbear567

For issue [29550](https://github.com/spring-projects/spring-boot/issues/29550).
Preliminary submission.

2022-01-26 18:34 UTC, philwebb commented
Thanks for the pull-request @polarbear567. When raising #29550 I was originally thinking we'd offer a way to do this programmatically. The properties are an interesting alternative that didn't occur to me and I'm now not sure which is best. I'm going to flag this for team discussion to see what other think.

2022-01-26 20:40 UTC, wilkinsona commented
I quite like the property-based approach. They do feel quite low-level but not so low that I think they ought to only be available programatically.

2022-01-31 09:03 UTC, snicoll requested changes
Thanks for the PR @polarbear567. We need tests that exercise those properties and validate they are mapped properly please. Would you have time to look at that?

2022-01-31 09:03 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/rsocket/RSocketProperties.java
> +			 * Sub-protocol to use in websocket handshake signature. Null by default.
There's no need to write "by default" in the description as we harvest defaults and process them separately.

2022-01-31 09:03 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/rsocket/RSocketProperties.java
> +			private int maxFramePayloadLength;
This field should be initialized  with `65536` then. Currently the advertised default is `0`.

2022-01-31 09:03 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/rsocket/RSocketProperties.java
> +			private boolean handlePing;
The second sentence should be removed as discussed above.

2022-01-31 09:03 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/rsocket/RSocketProperties.java
> +			 * request presents websocket extensions headers. By default compression is
Ditto.

2022-01-31 09:03 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/rsocket/RSocketWebSocketNettyRouteProvider.java
> +	RSocketWebSocketNettyRouteProvider(String mappingPath, Spec spec, SocketAcceptor socketAcceptor,
There's no need to assign the fieds here. keeping the `Spec` object should be enough.

2022-01-31 09:03 UTC, snicoll commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/rsocket/RSocketWebSocketNettyRouteProvider.java
> +		this.maxFramePayloadLength = (spec.getMaxFramePayloadLength() <= 0) ? 65536 : spec.getMaxFramePayloadLength();
This handling of the default here doesn't feel right to me.

2022-02-11 01:55 UTC, polarbear567 commented
Sure, I'll take a look at it when I'm free. I'll modify PR according to comments. I don't have any good ideas for testing. Do you have any suggestions? @snicoll

2022-02-11 08:42 UTC, snicoll commented
> I don't have any good ideas for testing. Do you have any suggestions?

Yeah good point, I didn't look far enough. The mapping is hidden behind the predicate so it's hard to test this way. We can look ourselves as part of merging this, thanks for the update!

2023-07-26 11:58 UTC, closed without merging