Add WebClient based sender for Zipkin
spring-projects/spring-boot pull request #30792
Opened 2022-04-25 14:17 UTC by StefanBratanov

## PR Description

- Introduce abstract `HttpSender` class
- Introduce `ZipkinWebClientSender`
- Add `ZipkinWebClientSender` bean to configuration

related to #30661

2022-04-25 14:17 UTC, pivotal-cla commented
@StefanBratanov Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=30792)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=30792) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-04-25 14:18 UTC, pivotal-cla commented
@StefanBratanov Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=30792)!

2022-05-03 06:37 UTC, wilkinsona commented
Nothing at the moment, @StefanBratanov. Moritz is out for a few weeks on paternity leave so it may take us a little while to get to it. 3.0 doesn't GA until November so there's no rush at this stage.

2022-05-03 06:42 UTC, StefanBratanov commented
> Nothing at the moment, @StefanBratanov. Moritz is out for a few weeks on paternity leave so it may take us a little while to get to it. 3.0 doesn't GA until November so there's no rush at this stage.

Sure. No worries. Thank you for quick update. Congratulations to Moritz. 🙂

2022-06-14 13:52 UTC, mhalbritter requested changes

2022-06-14 13:52 UTC, mhalbritter commented on spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/zipkin/ZipkinConfigurations.java
> +			WebClient webClient = webClientBuilder.clientConnector(new ReactorClientHttpConnector(client)).build();
This introduces a hard dependency on Netty, "just" for the sake of setting a timeout.

2022-06-14 13:52 UTC, mhalbritter commented on spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/zipkin/HttpSender.java
> +		byte[] body;
Can this be private final?

2022-06-14 13:52 UTC, mhalbritter commented on spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/zipkin/HttpSender.java
> +	volatile boolean closed;
Can this be private?

2022-06-14 13:52 UTC, mhalbritter commented on spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/zipkin/ZipkinWebClientSender.java
> +					}, (__) -> {
This looks wrong, the errors will be suppressed. The webclient and the Zipkin Sender interface both support callbacks, maybe we could refactor this to fix the error handling?

2022-06-14 13:52 UTC, mhalbritter commented on spring-boot-project/spring-boot-actuator-autoconfigure/src/test/java/org/springframework/boot/actuate/autoconfigure/tracing/zipkin/ZipkinWebClientSenderTests.java
> +		mockBackEnd = new MockWebServer();
Is this integration testing the only way to test webclients? RestTemplate has a built-in test infrastructure, I wonder if WebClient has the same?

2022-06-14 13:52 UTC, mhalbritter commented on spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/zipkin/ZipkinConfigurations.java
> +		@Bean
I have fixed a bug in `main` regarding the auto-configuration, I guess you'll have to rebase.

2022-06-14 13:53 UTC, mhalbritter commented
Hey, thanks for the contribution. I'm back and have some comments on the code.

2022-06-14 14:13 UTC, StefanBratanov commented
> Hey, thanks for the contribution. I'm back and have some comments on the code.

Welcome back! Thank you. I will have a look.

2022-06-21 11:32 UTC, mhalbritter commented on spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/zipkin/ZipkinRestTemplateSender.java
> +			CompletableFuture.supplyAsync(this::doExecute).whenComplete((__, throwable) -> {
We don't need the `CompletableFuture` in this case. The UrlConnectionSender implements the `enqueue` call without additional threading, so we should be fine here without introducing multi-threading.

2022-06-21 11:36 UTC, mhalbritter commented
Thanks @StefanBratanov for the changes, the PR looks quite nice now!

> Hi Moritz, sorry for the delay. I did make a refactor based on the comments, which i agree with. I wasn't sure about handling the `WebClient` async call, but now i think it makes sense and is cleaner. I also changed the `ZipkinRestTemplateSender` async implementation to use a `CompletableFuture` since it was blocking before. I also added tests for both sync and async in both implementations.

I don't think we need that. The `UrlConnectionSender` from zipkin implements the enqueue call without additional threading, so we should be fine here without introducing multi-threading.

> I am not sure about initializing the `WebClient` in `ZipkinConfigurations`. I was using the `ReactorClientHttpConnector` which is based on` Netty`, so that i can honor the read and connect timeouts set in `ZipkinProperties`. What do you think is a better approach for initializing the `WebClient`? 

I have to double check if there's really no way to set timeouts without tying us directly on the implementation.

> Also i couldn't find a mock server similar to `MockRestServiceServer` for `WebClient`, so kept my old implementation. If there is one, I am happy to change it.

Yes, I was wrong, there's no such support in the Spring Framework. The recommendation is to use the [OkHttp MockServer](https://docs.spring.io/spring-framework/docs/6.0.0-SNAPSHOT/reference/html/web-reactive.html#webflux-client-testing), like you did.

2022-06-21 14:28 UTC, StefanBratanov commented
Hi @mhalbritter thanks for review, I replaced the` CompletableFuture` implementation with a normal one. I will wait for you to check about the WebClient initialization. My logic was that `@ConditionalOnWebApplication(type = ConditionalOnWebApplication.Type.REACTIVE)` in _ZipkinConfigurations_ if true, should mean that Netty should be on the classpath. I could be wrong though.

2022-06-22 07:40 UTC, mhalbritter commented
Unfortunately, this is not the case. You can [use other servers for reactive applications](https://docs.spring.io/spring-boot/docs/3.0.0-SNAPSHOT/reference/htmlsingle/#web.reactive.reactive-server).

> Spring Boot includes support for the following embedded reactive web servers: Reactor Netty, Tomcat, Jetty, and Undertow

The best option would be to have timeout setter on the `WebClient.Builder`, but unfortunately this is not available [and won't be](https://github.com/spring-projects/spring-framework/issues/25115#issuecomment-677685984).

I would drop the timeout code in the configuration for now, and I will bring this up with the team if we can find a solution which works for all the connector implementations.

2022-06-22 07:50 UTC, StefanBratanov commented
> Unfortunately, this is not the case. You can [use other servers for reactive applications](https://docs.spring.io/spring-boot/docs/3.0.0-SNAPSHOT/reference/htmlsingle/#web.reactive.reactive-server).
> 
> > Spring Boot includes support for the following embedded reactive web servers: Reactor Netty, Tomcat, Jetty, and Undertow
> 
> The best option would be to have timeout setter on the `WebClient.Builder`, but unfortunately this is not available [and won't be](https://github.com/spring-projects/spring-framework/issues/25115#issuecomment-677685984).
> 
> I would drop the timeout code in the configuration for now, and I will bring this up with the team if we can find a solution which works for all the connector implementations.

Got it. Makes sense. Good to know! The default builder will take care of initialising the appropriate connector. I removed the Netty connector.

2022-06-22 08:26 UTC, closed without merging

2022-06-22 08:27 UTC, mhalbritter commented
I've merged your PR. Thanks for your work and congratulations on your first contribution to Spring Boot!