Migrates to sender and receiver propagation handlers
spring-projects/spring-boot pull request #31783
Opened 2022-07-18 10:58 UTC by marcingrzejszczak

Related PRs

- [ ] https://github.com/micrometer-metrics/micrometer/pull/3293
- [ ] https://github.com/micrometer-metrics/tracing/pull/36

2022-07-22 18:43 UTC, wilkinsona commented
To avoid being on snapshots for too long, we should merge this nearer the release of the next milestone.

2022-08-19 22:06 UTC, jonatan-ivanov requested changes

2022-08-19 22:06 UTC, jonatan-ivanov commented on spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/MicrometerTracingAutoConfiguration.java
> +	@ConditionalOnBean({ Tracer.class, Propagator.class })
This means that both receiver and sender handlers will be created if there is a propagator.

2022-08-19 22:06 UTC, jonatan-ivanov commented on spring-boot-project/spring-boot-actuator-autoconfigure/src/test/java/org/springframework/boot/actuate/autoconfigure/tracing/MicrometerTracingAutoConfigurationTests.java
> +		PropagatingReceiverTracingObservationHandler customPropagatingReceiverTracingObservationHandler() {
GH does not let me comment it, but a few lines above the `HttpServerHandler` and `HttpClientHandler` beans are not used but a `Propagator` bean is missing.

2022-09-07 08:13 UTC, wilkinsona commented
These changes were also included in https://github.com/spring-projects/spring-boot/pull/32048 which has now been merged.

2022-09-07 08:13 UTC, closed without merging