Switch from single topic for fixed delays to single topic for same intervals in Spring Kafka retry configuration.
spring-projects/spring-boot pull request #34504
Opened 2023-03-07 12:04 UTC by Abhijeetmishr

2023-03-07 12:04 UTC, pivotal-cla commented
@Abhijeetmishr Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=34504)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=34504) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-03-07 12:05 UTC, pivotal-cla commented
@Abhijeetmishr Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=34504)!

2023-03-07 14:46 UTC, garyrussell requested changes

2023-03-07 14:46 UTC, garyrussell commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaAutoConfiguration.java
> +			.useSingleTopicForSameIntervals()
Need to remove the `@SuppressWarnings` with this change.

2023-03-08 22:35 UTC, scottfrederick commented
This is blocked pending the `main` branch upgrading to Spring Kafka 3.0.4.

2023-03-09 05:14 UTC, Abhijeetmishr commented
> This is blocked pending the `main` branch upgrading to Spring Kafka 3.0.4.

@scottfrederick blocked because of release can I make changes which is required to fix this issue ?

2023-03-16 10:14 UTC, Abhijeetmishr commented
@garyrussell @scottfrederick PR is still needed or I should close it ?

2023-03-16 14:02 UTC, scottfrederick commented
@Abhijeetmishr This is still a change we want to make, it's just not our highest priority. I'll merge this PR soon.

2023-03-16 16:49 UTC, Abhijeetmishr commented
> @Abhijeetmishr This is still a change we want to make, it's just not our highest priority. I'll merge this PR soon.

I was confirming because I have to update this PR.
Thank you!

2023-03-21 18:50 UTC, closed without merging