changing yml to yaml for consistency
spring-projects/spring-boot pull request #34628
Opened 2023-03-17 07:23 UTC by ivandimitrov8080

#34624

Changed most yml to yaml, except for this one:
```
`The following example `scrape_config` adds to `prometheus.yml`:
```

And this one:
```
|YAML
| `com.fasterxml.jackson.core:jackson-databind` + `com.fasterxml.jackson.dataformat:jackson-dataformat-yaml`
| `log4j2.yaml` + `log4j2.yml`

|JSON
| `com.fasterxml.jackson.core:jackson-databind`
| `log4j2.json` + `log4j2.jsn`
|===
```

The [prometheus docs](https://prometheus.io/docs/introduction/first_steps/#configuring-prometheus) refer to their config file as `prometheus.yml`.

The log4j example looks consistent enough with what is below it.

2023-03-17 07:23 UTC, pivotal-cla commented
@ivandimitrov8080 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=34628)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=34628) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-03-17 07:24 UTC, pivotal-cla commented
@ivandimitrov8080 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=34628)!

2023-03-17 11:33 UTC, wilkinsona requested changes
Thanks for the PR, @ivandimitrov8080. I've left a few comments for your consideration.

2023-03-17 11:33 UTC, wilkinsona commented on spring-boot-project/spring-boot-docs/src/docs/asciidoc/io/hazelcast.adoc
> +* A `hazelcast-client.yaml` in the working directory or at the root of the classpath.
I don't think this change is necessary. Hazelcast supports both and the current docs indicate that `.yaml` is preferred.

2023-03-17 11:33 UTC, wilkinsona commented on spring-boot-project/spring-boot-docs/src/docs/asciidoc/io/hazelcast.adoc
> +Otherwise, Spring Boot tries to find the Hazelcast configuration from the default locations: `hazelcast.xml` in the working directory or at the root of the classpath, or a `.yaml` counterpart in the
I would change this to "or a YAML counterpart" rather than repeating the file extension(s).

2023-03-17 11:33 UTC, wilkinsona commented on spring-boot-project/spring-boot-docs/src/docs/asciidoc/using/devtools.adoc
> -. `spring-boot-devtools.yml`
This should not change as we still look for `.yml` files. The current ordering suggests that `.yaml` is preferred so it is fine as-is.

2023-03-17 11:33 UTC, wilkinsona commented on spring-boot-project/spring-boot-docs/src/docs/asciidoc/features/external-config.adoc
> +If you have configuration files with both `.properties` and `.yaml` format in the same location, `.properties` takes precedence.
Both `.yml` and `.yaml` are still supported. I think it would be better to say "and YAML format".

2023-03-17 11:33 UTC, wilkinsona commented on spring-boot-project/spring-boot-docs/src/docs/asciidoc/features/external-config.adoc
> +| Kebab case, which is recommended for use in `.properties` and `.yaml` files.
I think "and YAML files" would be better here.

2023-03-17 11:33 UTC, wilkinsona commented on spring-boot-project/spring-boot-docs/src/docs/asciidoc/features/external-config.adoc
> +| Underscore notation, which is an alternative format for use in `.properties` and `.yaml` files.
I think "and YAML files" would be better here.

2023-03-17 11:33 UTC, wilkinsona commented on spring-boot-project/spring-boot-docs/src/docs/asciidoc/howto/properties-and-configuration.adoc
> +By default, if YAML is used, then files with the '`.yaml`' extension are also added to the list.
'`.yaml`' and '`.yml`' extensions are also added to the list

2023-03-17 11:33 UTC, wilkinsona commented on spring-boot-project/spring-boot-docs/src/docs/asciidoc/howto/properties-and-configuration.adoc
> +Spring Boot binds external properties from `application.properties` (or `.yaml` files and other places) into an application at runtime.
"or YAML files and other places" might be better here

2023-04-24 11:47 UTC, closed without merging

2023-04-24 11:47 UTC, snicoll commented
@ivandimitrov8080 thank you for making your first contribution to Spring Boot.