optimize code with complex and outdated iterator loop
spring-projects/spring-boot pull request #34762
Opened 2023-03-25 15:02 UTC by SeasonPanPan

Hello, I saw several complex and outdated **iterator loops** used in the code while learning the spring boot source code. 

I think this can be optimized for a more concise code. 

Please review it. Thank you for your time.

2023-03-27 12:05 UTC, wilkinsona requested changes
Thanks very much for the PR. I've left a comment for your consideration when you have some time.

2023-03-27 12:05 UTC, wilkinsona commented on spring-boot-project/spring-boot-tools/spring-boot-configuration-processor/src/json-shade/java/org/springframework/boot/configurationprocessor/json/JSONArray.java
Can you please revert this part of the change. This is a shaded copy of third-party source and we want to leave it as originally written.

2023-03-27 14:07 UTC, SeasonPanPan commented
> Thanks very much for the PR. I've left a comment for your consideration when you have some time.

@wilkinsona Done, please check.

2023-04-11 14:39 UTC, closed without merging

2023-04-11 14:40 UTC, snicoll commented
@SeasonPanPan thank you for making your first contribution to Spring Boot.