Fix JacksonJsonpMapper bean autoconfigure condition bug
spring-projects/spring-boot pull request #36109
Opened 2023-06-29 08:03 UTC by Pengfei-Lu

Fix #36107.

2023-06-29 09:39 UTC, Pengfei-Lu commented
I don't know how to mock the "ObjectMapper class is not loaded" senario, thus deleting the two failed `withoutJsonbOrJacksonShouldDefineSimpleMapper` & `withJsonbShouldDefineJsonbMapper` tests cases.

Is there any better solution?

2023-06-29 09:46 UTC, wilkinsona commented
You should be able to use `contextRunner.withClassLoader(new FilteredClassLoader(ObjectMapper.class))`.

2023-06-29 09:55 UTC, Pengfei-Lu commented
> You should be able to use `contextRunner.withClassLoader(new FilteredClassLoader(ObjectMapper.class))`.

It works! Please review the code.

2023-06-29 10:09 UTC, wilkinsona requested changes
Thanks for the updates, @Pengfei-Lu. I think `ElasticsearchClientAutoConfiguration` could also be updated as it no longer needs to be ordered after `JacksonAutoConfiguration`. Could you do that as well please?

2023-06-30 01:12 UTC, Pengfei-Lu commented
> Thanks for the updates, @Pengfei-Lu. I think `ElasticsearchClientAutoConfiguration` could also be updated as it no longer needs to be ordered after `JacksonAutoConfiguration`. Could you do that as well please?

Done. Please check.

2023-07-03 07:26 UTC, Pengfei-Lu commented
@wilkinsona If there is any update, please let me know, thanks!

2023-07-12 14:28 UTC, wilkinsona approved these changes

2023-07-14 09:43 UTC, closed without merging

2023-07-14 13:07 UTC, wilkinsona commented
Thanks very much for the PR, @Pengfei-Lu.