Docs: server.forward-headers-strategy property defaults to NATIVE also for k8s
spring-projects/spring-boot pull request #36564
Opened 2023-07-25 12:13 UTC by MahatmaFatalError

I found that my app on k8s has `server.forward-headers-strategy` NATIVE but the docs do not state so.
Hence I propose this quick fix.

2023-07-25 13:25 UTC, wilkinsona requested changes

2023-07-25 13:25 UTC, wilkinsona commented on spring-boot-project/spring-boot-docs/src/docs/asciidoc/howto/webserver.adoc
> +NOTE: If your application runs in Cloud Foundry, Heroku or K8s, the configprop:server.forward-headers-strategy[] property defaults to `NATIVE`.
Thanks for the suggestion. I think it would be better to use Kubernetes here rather than the K8S abbreviation.

2023-07-25 17:13 UTC, wilkinsona approved these changes
Looks good to me. Thanks for the update, @MahatmaFatalError. Can you please remove the draft status from the PR?

2023-07-26 07:54 UTC, mhalbritter commented
Thank you very much and congratulations on your first contribution :tada:!

2023-07-26 07:54 UTC, closed without merging