Update docker-compose doc with test support #35661
spring-projects/spring-boot pull request #36636
Opened 2023-07-28 13:05 UTC by OnSuorce

Added note to indicate how to enable support for spring docker compose module in @SpringBootTest tests

2023-07-28 13:05 UTC, pivotal-cla commented
@OnSuorce Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=36636)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=36636) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-07-28 13:06 UTC, pivotal-cla commented
@OnSuorce Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=36636)!

2023-07-28 13:13 UTC, OnSuorce commented
Hi,
Did i write the pull request message wrongly? It seems to me that the issue #35661  was not recognized.

2023-07-28 13:46 UTC, wilkinsona commented
No, everything's fine. I don't think GitHub lets you reference an issue from the title of an issue or PR, that's all. Thanks for the PR.

2023-07-28 13:50 UTC, wilkinsona requested changes

2023-07-28 13:50 UTC, wilkinsona commented on spring-boot-project/spring-boot-docs/src/docs/asciidoc/features/docker-compose.adoc
> +NOTE: If you wish to run docker compose via `spring-boot-docker-compose` when using `@SpringBootTest` 's tests, the property `spring.docker.compose.skip.in-tests` must be set to `false`
Can you please replace `` `spring.docker.compose.skip.in-tests` `` with `configprop:spring.docker.compose.skip.in-tests[]`. `configprop` is a macro that runs as part of building the documentation. It verifies that the configuration property exists, helping to ensure the accuracy of the documentation.

2023-07-28 13:51 UTC, OnSuorce commented
> No, everything's fine. I don't think GitHub lets you reference an issue from the title of an issue or PR, that's all. Thanks for the PR.

Ok, next time i'll reference it from the description

2023-07-31 09:05 UTC, closed without merging

2023-07-31 09:06 UTC, wilkinsona commented
@OnSuorce thank you very much for making your first contribution to Spring Boot.

2023-07-31 15:02 UTC, OnSuorce commented
@wilkinsona Thank you for your help. Looking forward to contributing again