Fix handling of nodes with IPv6 addresses for Redis sentinel and cluster auto-config
spring-projects/spring-boot pull request #39819
Opened 2024-03-01 18:26 UTC by tobi-laa

When specifying colon-separated pairs of host and port with IPv6 addresses (i.e. `[::1]:6379`) for either `spring.data.redis.cluster.nodes` or `spring.data.redis.sentinel.nodes`, the parsing of these nodes/addresses was broken as the splitting of these strings was not performed explicitly on the last found colon. The behavior is fixed with this PR.

2024-03-01 18:26 UTC, pivotal-cla commented
@tobi-laa Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=39819)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=39819) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-03-01 18:28 UTC, pivotal-cla commented
@tobi-laa Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=39819)!

2024-03-04 18:03 UTC, tobi-laa commented
Fixed formatting.

2024-03-07 20:32 UTC, tobi-laa commented
Fixed Checkstyle violation. Sorry, should have fixed that from the start.

2024-03-08 08:56 UTC, mhalbritter commented
If you run `./gradlew build`, you get those errors on your local machine instead of waiting for the CI.

2024-03-15 17:32 UTC, wilkinsona requested changes

2024-03-15 17:32 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/PropertiesRedisConnectionDetails.java
> +		var host = node.substring(0, posLastColon).replaceFirst("^\\[(.+)]$", "$1");
I don't think the `[` and `]` should be removed. They can be useful in situations where the `:` characters in an address can cause problems. We should trust the user to have used them in the property's value intentionally.

I think we can just use code that's very similar to `PropertiesRabbitConnectionDetails`:

https://github.com/spring-projects/spring-boot/blob/9a4d0fb8b62aac303e9879f625cf4e7a4cf43cbc/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/amqp/PropertiesRabbitConnectionDetails.java#L56-L59

2024-03-15 17:32 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/PropertiesRedisConnectionDetails.java
> +		var posLastColon = node.lastIndexOf(':');
We don't use `var` in Spring Boot's codebase.

2024-03-19 22:13 UTC, tobi-laa commented
@wilkinsona Thank you for the review! I updated the PR accordingly.

2024-04-22 11:11 UTC, closed without merging

2024-04-22 11:11 UTC, wilkinsona commented
@tobi-laa thanks very much for making your first contribution to Spring Boot.