Replace lambda with method reference
spring-projects/spring-boot pull request #40974
Opened 2024-06-03 07:55 UTC by asashour

This PR replaces lambda with method reference whenever possible.

There are other small changes, like
- using `switch` instead of `if`
- remove unnecessary (un)boxing
- Use Map.of() and List.of() for unmodifiable collections.

2024-06-03 08:50 UTC, wilkinsona requested changes

2024-06-03 08:50 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration.java
> +				.to(extension.via(PostgreSQLConfigurationExtension::setTransactionalLock));
Please revert these changes. We deliberately do not use method references when configuration Flyway to improve backwards- and forwards-compatibility (see https://github.com/spring-projects/spring-boot/issues/38164).

2024-06-03 08:50 UTC, wilkinsona commented on spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/ArtifactsLibraries.java
> +		SCOPES = Map.of(Artifact.SCOPE_COMPILE, LibraryScope.COMPILE, Artifact.SCOPE_RUNTIME, LibraryScope.RUNTIME, Artifact.SCOPE_PROVIDED, LibraryScope.PROVIDED, Artifact.SCOPE_SYSTEM, LibraryScope.PROVI
Like https://github.com/spring-projects/spring-boot/pull/38352, I prefer this as currently written as I think it's easier to read. Please revert.

2024-06-03 08:50 UTC, wilkinsona commented on spring-boot-project/spring-boot/src/main/java/org/springframework/boot/ansi/AnsiPropertySource.java
> +				new EnumMapping<>("Ansi.BG_", AnsiBackground.class));
This has been [proposed and declined](https://github.com/spring-projects/spring-boot/pull/38352) in the past. Please revert.

2024-06-03 08:50 UTC, wilkinsona commented on spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/ApplicationPidFileWriter.java
> +				new SystemProperty("PIDFILE"));
Similar to https://github.com/spring-projects/spring-boot/pull/38352. Please revert.

2024-06-03 08:50 UTC, wilkinsona commented on spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/ApplicationPidFileWriter.java
> +				new SystemProperty("PID_FAIL_ON_WRITE_ERROR"));
Similar to https://github.com/spring-projects/spring-boot/pull/38352. Please revert.

2024-06-03 18:17 UTC, philwebb commented
When we merge this I think we should convert it into distinct commits for the method refs vs other stuff.

2024-06-04 01:18 UTC, asashour commented
In this case, this PR would contain the method reference, and I would create a new one for the other changes, thanks.

2024-06-04 07:31 UTC, wilkinsona requested changes
Thanks for the updates, @asashour. I just noticed one other change that I think would improve things a little. Please see the comments for details.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-web-secure/src/test/java/smoketest/web/secure/SampleWebSecureApplicationTests.java
> +			http.csrf(AbstractHttpConfigurer::disable);
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-web-secure-jdbc/src/main/java/smoketest/web/secure/jdbc/SampleWebSecureJdbcApplication.java
> +			http.csrf(AbstractHttpConfigurer::disable);
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-web-secure-custom/src/main/java/smoketest/web/secure/custom/SampleWebSecureCustomApplication.java
> +			http.csrf(AbstractHttpConfigurer::disable);
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-web-method-security/src/main/java/smoketest/security/method/SampleMethodSecurityApplication.java
> +			http.csrf(AbstractHttpConfigurer::disable);
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-web-method-security/src/main/java/smoketest/security/method/SampleMethodSecurityApplication.java
> +			http.csrf(AbstractHttpConfigurer::disable);
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-session-redis/src/main/java/smoketest/session/redis/SecurityConfiguration.java
> +		http.csrf(AbstractHttpConfigurer::disable);
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-session-mongo/src/main/java/smoketest/session/mongodb/SecurityConfiguration.java
> +		http.csrf(AbstractHttpConfigurer::disable);
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-session-jdbc/src/main/java/smoketest/session/SecurityConfiguration.java
> +		http.csrf(AbstractHttpConfigurer::disable);
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-session-hazelcast/src/main/java/smoketest/session/hazelcast/SecurityConfiguration.java
> +		http.csrf(AbstractHttpConfigurer::disable);
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-graphql/src/main/java/smoketest/graphql/SecurityConfig.java
> +		return http.csrf(AbstractHttpConfigurer::disable)
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-actuator/src/test/java/smoketest/actuator/ShutdownSampleActuatorApplicationTests.java
> +			http.csrf(AbstractHttpConfigurer::disable);
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-project/spring-boot-docs/src/main/java/org/springframework/boot/docs/data/sql/h2webconsole/springsecurity/DevProfileSecurityConfiguration.java
> +		http.csrf(AbstractHttpConfigurer::disable);
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/autoconfigure/RemoteDevtoolsSecurityConfiguration.java
> +		http.csrf(AbstractHttpConfigurer::disable);
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 07:31 UTC, wilkinsona commented on spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/graphql/security/GraphQlWebMvcSecurityAutoConfigurationTests.java
> +			return http.csrf(AbstractHttpConfigurer::disable)
I think `CsrfConfigurer::disable` would read better here.

2024-06-04 08:50 UTC, asashour commented
If I may say something, there is an error for some time that `No space left on device`. I am not sure if this is related to the PR content.

2024-06-11 20:32 UTC, closed without merging

2024-06-11 20:33 UTC, philwebb commented
Thanks @asashour