Correct grammar in Javadoc
spring-projects/spring-boot pull request #41443
Opened 2024-07-10 20:12 UTC by jxblum

Fixed grammatical issues in Javadoc for the `BootstrapContext` interface.

Closes PR #41443

2024-07-10 21:08 UTC, codespearhead reviewed
LGTM.

For what it's worth, I noticed those typos are present in a lot of places in the codebase [1][2]. 

https://github.com/spring-projects/spring-boot/blob/09c0714730f482560b7e2cbb04cb05b7b97aea86/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/system/JavaVersion.java#L104-L111

https://github.com/spring-projects/spring-boot/blob/09c0714730f482560b7e2cbb04cb05b7b97aea86/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/server/Ssl.java#L323-L331

https://github.com/spring-projects/spring-boot/blob/09c0714730f482560b7e2cbb04cb05b7b97aea86/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/origin/OriginLookup.java#L39-L46

But not everywhere:

https://github.com/spring-projects/spring-boot/blob/09c0714730f482560b7e2cbb04cb05b7b97aea86/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/DefaultPropertiesPropertySource.java#L54-L61

https://github.com/spring-projects/spring-boot/blob/09c0714730f482560b7e2cbb04cb05b7b97aea86/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigDataProperties.java#L65-L73

***

[1] https://github.com/search?q=repo%3Aspring-projects%2Fspring-boot+%22*+Return+if+%22&type=code&p=1
[2] https://github.com/search?q=repo%3Aspring-projects%2Fspring-boot+%22*+%40return+if+%22&type=code

2024-07-11 06:47 UTC, wilkinsona requested changes

2024-07-11 06:47 UTC, wilkinsona commented on spring-boot-project/spring-boot/src/main/java/org/springframework/boot/BootstrapContext.java
> +	 * Return {@code true} if a registration exists for the given type.
While we aren't consistent across the codebase, I don't consider this one to be a typo or grammatical error. We should leave it as is for now please.

2024-07-11 12:18 UTC, closed without merging

2024-07-11 12:19 UTC, wilkinsona commented on spring-boot-project/spring-boot/src/main/java/org/springframework/boot/BootstrapContext.java
> +	 * Return {@code true} if a registration exists for the given type.
No need to do anything here. I dropped this change while merging the PR.

2024-07-11 12:19 UTC, wilkinsona commented
Thanks very much, @jxblum.