Add support for Postgres trust auth method at docker compose
spring-projects/spring-boot pull request #41511
Opened 2024-07-16 03:27 UTC by theodorosidmar

Fixes #41509

2024-07-16 07:31 UTC, wilkinsona requested changes
Thanks for the PR, @theodorosidmar. I've left a few comments for your consideration.

2024-07-16 07:31 UTC, wilkinsona commented on spring-boot-project/spring-boot-docker-compose/src/main/java/org/springframework/boot/docker/compose/service/connection/postgres/PostgresEnvironment.java
> +		String postgresAuthMethod = env.getOrDefault("POSTGRES_HOST_AUTH_METHOD", "password");
I don't think a default is needed here so this could just use `get`.

2024-07-16 07:31 UTC, wilkinsona commented on spring-boot-project/spring-boot-docker-compose/src/main/java/org/springframework/boot/docker/compose/service/connection/postgres/PostgresEnvironment.java
> +		return Objects.equals(postgresAuthMethod, "trust");
We don't really use `Objects.equals`. This could be `return "trust".equals(postgresAuthMethod);` instead.

2024-07-16 07:31 UTC, wilkinsona commented on spring-boot-project/spring-boot-docker-compose/src/test/java/org/springframework/boot/docker/compose/service/connection/postgres/PostgresEnvironmentTests.java
> +	void getPasswordWhenHasTrustAuthMethod() {
`getPasswordWhenHasTrustHostAuthMethod()`

2024-07-16 07:31 UTC, wilkinsona commented on spring-boot-project/spring-boot-docker-compose/src/main/java/org/springframework/boot/docker/compose/service/connection/postgres/PostgresEnvironment.java
> +		String postgresAuthMethod = env.getOrDefault("POSTGRES_HOST_AUTH_METHOD", "password");
For consistency, I'd rename `postgresAuthMethod` to `hostAuthMethod`.

2024-07-16 12:17 UTC, theodorosidmar commented
Awesome. Thank you for the review. Here you go: https://github.com/spring-projects/spring-boot/pull/41511/commits/8e9a4825beef5d2afb7cde16e5ca0e16e14baecc

2024-07-16 18:18 UTC, wilkinsona approved these changes

2024-07-16 18:43 UTC, closed without merging

2024-07-16 18:43 UTC, wilkinsona commented
Thanks very much, @theodorosidmar, and congratulations on making your first contribution to Spring Boot.

2024-07-16 18:49 UTC, theodorosidmar commented
I should be thanking you. Thank you for your attention. Glad to contribute.

2024-09-12 15:11 UTC, mshima commented
@wilkinsona can this PR be backported to 3.3.x?

2024-09-12 15:18 UTC, wilkinsona commented
I'm afraid not. We don't backport enhancements to maintenance branches.