Refactor code and update documentation
spring-projects/spring-boot pull request #42192
Opened 2024-09-09 13:25 UTC by arefbehboudi

- Removed @SuppressWarnings as it was no longer needed.
- Used pattern matching.
- Updated documentation.
- Replaced class with record.

2024-09-09 13:45 UTC, wilkinsona requested changes

2024-09-09 13:45 UTC, wilkinsona commented on spring-boot-project/spring-boot/src/main/java/org/springframework/boot/rsocket/context/RSocketPortInfoApplicationContextInitializer.java
> +	private record Listener(ConfigurableApplicationContext applicationContext) implements ApplicationListener<RSocketServerInitializedEvent> {
Making this a `record` adds an accessor for the application context which we don't want. Please revert.

2024-09-09 13:45 UTC, wilkinsona commented on spring-boot-project/spring-boot/src/main/java/org/springframework/boot/json/JsonValueWriter.java
> +			append(bool ? "true" : "false");
I think it would be better to use `toString()` here. It could then be combined with the handling of `Number`.

2024-09-09 13:45 UTC, wilkinsona commented on spring-boot-project/spring-boot/src/main/java/org/springframework/boot/jdbc/DataSourceBuilder.java
> -		@SuppressWarnings("unchecked")
Removing this results in a warnings with `javac`:

```
 warning: [unchecked] unchecked method invocation: method add in class MappedDataSourceProperties is applied to given types
                        add(DataSourceProperty.DRIVER_CLASS_NAME, Class.class, (dataSource) -> dataSource.getDriver().getClass(),
                           ^
  required: DataSourceProperty,Class<V>,Getter<T,V>,Setter<T,V>
  found:    DataSourceProperty,Class<Class>,Getter<SimpleDriverDataSource,Class>,Setter<SimpleDriverDataSource,Class>
  where V,T are type-variables:
    V extends Object declared in method <V>add(DataSourceProperty,Class<V>,Getter<T,V>,Setter<T,V>)
    T extends DataSource declared in class MappedDataSourceProperties
error: warnings found and -Werror specified
1 error
1 warning
```

Please revert.

2024-09-10 08:40 UTC, arefbehboudi commented
Thanks for the review. I've updated the code based on your feedback. Please check it again when you can.

2024-09-10 10:54 UTC, closed without merging

2024-09-10 10:55 UTC, snicoll commented
@arefbehboudi thanks for the contribution. It wasn't building as the formatting was no longer correct. FTR you could have seen that locally by building the module, something like:

```
./gradlew :spring-boot-project:spring-boot:check
```

I've polished things in https://github.com/spring-projects/spring-boot/commit/ece5c6fe9e613831d2f0b2dd67ee4f7aa3828c76

2024-09-10 12:02 UTC, arefbehboudi commented
@snicoll Thanks for pointing that out! I'll make sure to run the build locally using the provided command to catch any formatting issues in the future. Thanks again for the guidance!