feat: add maxFormKeys for jetty
spring-projects/spring-boot pull request #42448
Opened 2024-09-25 15:53 UTC by qingbozhang

I encountered an issue in the project related to form submissions, where the number of keys exceeded Jetty's default limit of 1000. I found that there's no way to configure this parameter in the Spring Boot configuration file. 

Although I achieved my goal by setting `org.eclipse.jetty.server.Request.maxFormKeys`, it doesn't feel like an ideal solution. 
May I submit a PR to add this configuration option?

2024-09-25 15:53 UTC, pivotal-cla commented
@qingbozhang Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=42448)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-boot&pullRequestId=42448) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2024-09-25 15:54 UTC, pivotal-cla commented
@qingbozhang Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-boot&pullRequestId=42448)!

2024-09-27 06:17 UTC, qingbozhang commented
Hi  I’d appreciate a review when you have a moment. Thanks!

2024-09-27 07:03 UTC, wilkinsona commented
We're a small team with many different priorities. Expecting a review within two days of opening a PR isn't realistic. Someone will review this when we have time. Thank you for your patience in the meantime.

2024-09-27 08:21 UTC, qingbozhang commented
OK, thank you

2024-09-30 13:01 UTC, snicoll requested changes
Thanks for the PR, please review the comments when time permits.

2024-10-02 14:25 UTC, qingbozhang commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java
> +		 * Maximum size of the form keys.
Very correct, agree

2024-10-02 14:27 UTC, qingbozhang commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/ServerProperties.java
> +			return maxFormKeys;
OK

2024-10-02 15:51 UTC, qingbozhang commented on spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/embedded/JettyWebServerFactoryCustomizer.java
> +				.when(this::isPositive)
I add a test case `org.springframework.boot.autoconfigure.web.embedded.JettyWebServerFactoryCustomizerTests#customMaxFormKeys`. Passed assert

2024-10-02 16:05 UTC, qingbozhang commented
> Thanks for the PR, please review the comments when time permits.

Thanks for the feedback! I've made the suggested changes. Please let me know if anything else is needed.

2024-10-03 04:26 UTC, closed without merging

2024-10-03 04:26 UTC, philwebb commented
Thanks very much @qingbozhang